# limit

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, -0.1]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.0, 0.00, 0.0,  0.0, 0.00, 0.00,  0.0, 0.00, 0.0,  0.00, 0.00, 0.0]
step_height     = [0.0, 0.0, 0.0, 0.0]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080


# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080
# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080


# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080
# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080
# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080
# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080


# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080
# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080
# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080


# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080
# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080
# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.1, 0.0, -0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.05, 0.0, -0.1]
landing_pos_des = [0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0,  0.1, 0.00, 0.0]
step_height     = [0.06, 0.06, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 80
duration        = 1080
