# UpSlope20

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.15, 0.0, 0.0]
body_pos_des    = [0.0, -0.09, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.00, 0.00, 0.0,  0.08, 0.00, 0.03,  0.08, 0.00, 0.0,  0.00, 0.00, 0.0]
step_height     = [0.20, 0.20, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 1
landing_gain    = 1.0 
gait_id         = 81
duration        = 720

# 2
[[step]]
type            = "usergait"
body_vel_des    = [0.12, 0.0, 0.0]
body_pos_des    = [0.0, -0.09, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.12, 0.00, 0.04,  0.00, 0.00, 0.0,  0.00, 0.00, 0.0,  0.12, 0.00, 0.0]
step_height     = [0.20, 0.20, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 1
landing_gain    = 1.0 
gait_id         = 81
duration        = 720

# 3
[[step]]
type            = "usergait"
body_vel_des    = [0.12, 0.0, 0.0]
body_pos_des    = [0.0, -0.09, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.00, 0.00, 0.0,  0.04, 0.00, 0.15,  0.06, 0.00, 0.225,  0.00, 0.00, 0.0]
step_height     = [0.30, 0.30, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 1
landing_gain    = 1.0 
gait_id         = 81
duration        = 720

# 4
[[step]]
type            = "usergait"
body_vel_des    = [0.12, 0.0, 0.0]
body_pos_des    = [0.0, -0.09, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.04, 0.00, 15,  0.00, 0.00, 0.0,  0.00, 0.00, 0.0,  0.06, 0.00, 0.0]
step_height     = [0.30, 0.30, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 1
landing_gain    = 1.0 
gait_id         = 81
duration        = 720

# 5
[[step]]
type            = "usergait"
body_vel_des    = [0.13, 0.0, 0.0]
body_pos_des    = [0.0, -0.09, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.06, 0.00, 0.225,  0.06, 0.00, 0.225,  0.06, 0.00, 0.0,  0.06, 0.00, 0.0]
step_height     = [0.13, 0.13, 0.13, 0.13]
use_mpc_traj    = 1
mu              = 1
landing_gain    = 1.0 
gait_id         = 81
duration        = 28800
