# DownSlope20

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.07, 0.0, 0.0]
body_pos_des    = [0.0, 0.04, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.00, 0.00, 0.0,  0.02, 0.00, -0.1,  0.04, 0.00, 0.0,  0.00, 0.00, 0.0]
step_height     = [0.02, 0.02, 0.1, 0.1]
use_mpc_traj    = 1
mu              = 0.90
landing_gain    = 1.0 
gait_id         = 82
duration        = 720

# 2
[[step]]
type            = "usergait"
body_vel_des    = [0.07, 0.0, 0.0]
body_pos_des    = [0.0, 0.08, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.02, 0.00, -0.1,  0.00, 0.00, 0.0,  0.00, 0.00, 0.0,  0.04, 0.00, 0.0]
step_height     = [0.02, 0.02, 0.1, 0.1]
use_mpc_traj    = 1
mu              = 0.90
landing_gain    = 1.0 
gait_id         = 82
duration        = 720

# 3
[[step]]
type            = "usergait"
body_vel_des    = [0.03, 0.0, 0.0]
body_pos_des    = [0.0, 0.10, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.00, 0.00, 0.0,  0.01, 0.00, -0.1,  0.04, 0.00, 0.0,  0.00, 0.00, 0.0]
step_height     = [0.01, 0.01, 0.1, 0.1]
use_mpc_traj    = 1
mu              = 0.90
landing_gain    = 1.0 
gait_id         = 82
duration        = 720

# 4
[[step]]
type            = "usergait"
body_vel_des    = [0.03, 0.0, 0.0]
body_pos_des    = [0.0, 0.10, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.01, 0.00, -0.1,  0.00, 0.00, 0.0,  0.00, 0.00, 0.0,  0.04, 0.00, 0.0]
step_height     = [0.01, 0.01, 0.01, 0.01]
use_mpc_traj    = 1
mu              = 0.90
landing_gain    = 1.0 
gait_id         = 82
duration        = 720

# 5
[[step]]
type            = "usergait"
body_vel_des    = [0.05, 0.0, 0.0]
body_pos_des    = [0.0, 0.17, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.04, 0.00, -0.1,  0.04, 0.00, -0.1,  0.05, 0.00, -0.1,  0.05, 0.00, -0.1]
step_height     = [0.01, 0.01, 0.01, 0.01]
use_mpc_traj    = 1
mu              = 0.95
landing_gain    = 1.0 
gait_id         = 82
duration        = 17280
