# UpSlope20

# 1
[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 2

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 3
[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 4

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 5

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 6

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 7

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 8

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 9

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 10

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 11

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 12

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 13

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 14

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 15

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 16

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 17

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 18

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 19

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 20

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 21

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 22

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 23

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

# 24

[[section]]
contact  = [1, 0, 0, 1]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12

[[section]]
contact  = [0, 1, 1, 0]
duration = 12

[[section]]
contact  = [1, 1, 1, 1]
duration = 12