#upstairs10



#1
[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9


#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9






#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9
#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9
#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9






#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9
#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9
#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9






#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9
#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9
#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9






#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9
#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9
#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

#1
[[section]]
contact  = [1, 0, 0, 1]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [0, 1, 1, 0]
duration = 9

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

