# UpSlope20

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.15, 0.0, 0.0]
body_pos_des    = [0.0, -0.09, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.00, 0.00, 0.0,  0.08, 0.00, 0.1,  0.08, 0.00, 0.0,  0.00, 0.00, 0.0]
step_height     = [0.20, 0.20, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.70
landing_gain    = 1.0 
gait_id         = 92
duration        = 720

# 2
[[step]]
type            = "usergait"
body_vel_des    = [0.12, 0.0, 0.0]
body_pos_des    = [0.0, -0.18, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.12, 0.00, 0.1,  0.00, 0.00, 0.0,  0.00, 0.00, 0.0,  0.12, 0.00, 0.0]
step_height     = [0.20, 0.20, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.80
landing_gain    = 1.0 
gait_id         = 92
duration        = 720

# 3
[[step]]
type            = "usergait"
body_vel_des    = [0.12, 0.0, 0.0]
body_pos_des    = [0.0, -0.27, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.00, 0.00, 0.0,  0.04, 0.00, 0.1,  0.06, 0.00, 0.1,  0.00, 0.00, 0.0]
step_height     = [0.30, 0.30, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.80
landing_gain    = 1.0 
gait_id         = 92
duration        = 720

# 4
[[step]]
type            = "usergait"
body_vel_des    = [0.12, 0.0, 0.0]
body_pos_des    = [0.0, -0.36, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.04, 0.00, 1,  0.00, 0.00, 0.0,  0.00, 0.00, 0.0,  0.06, 0.00, 0.0]
step_height     = [0.30, 0.30, 0.05, 0.05]
use_mpc_traj    = 1
mu              = 0.80
landing_gain    = 1.0 
gait_id         = 92
duration        = 720

# 5
[[step]]
type            = "usergait"
body_vel_des    = [0.13, 0.0, 0.0]
body_pos_des    = [0.0, -0.38, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.06, 0.00, 1,  0.06, 0.00, 1,  0.06, 0.00, 0.0,  0.06, 0.00, 0.0]
step_height     = [0.13, 0.13, 0.13, 0.13]
use_mpc_traj    = 1
mu              = 0.80
landing_gain    = 1.0 
gait_id         = 92
duration        = 17280